/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    treks: Trek;
    users: User;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    treks: TreksSelect<false> | TreksSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    landing_page: LandingPage;
    treks_page: TreksPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    landing_page: LandingPageSelect<false> | LandingPageSelect<true>;
    treks_page: TreksPageSelect<false> | TreksPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treks".
 */
export interface Trek {
  id: string;
  /**
   * Full trek name shown on cards and detail pages.
   */
  name: string;
  /**
   * URL slug (auto-filled from name if left blank).
   */
  slug: string;
  /**
   * Primary cover photo (≥ 1 200 × 800 px). Appears in cards and as the hero banner.
   */
  heroImage: string | Media;
  /**
   * Select or drag-and-drop images at once. No per-image metadata.
   */
  gallery: (string | Media)[];
  /**
   * Package cost in the selected currency.
   */
  price: {
    /**
     * Numeric price without commas or separators.
     */
    amount: number;
    /**
     * Currency code for the price.
     */
    currency: 'NPR' | 'USD' | 'EUR' | 'GBP' | 'INR' | 'AUD' | 'CAD';
  };
  /**
   * Total trekking days (do not count arrival/departure buffer days).
   */
  durationDays: number;
  /**
   * One‑paragraph teaser (≈ 150 characters). Used in search results and SEO meta description.
   */
  summary: string;
  /**
   * Exactly three ultra‑short selling points (e.g. “12 d / 130 km”, “Sherpa culture”, “Hot springs”).
   */
  highlights: {
    /**
     * Single highlight phrase.
     */
    value: string;
    id?: string | null;
  }[];
  /**
   * Everything covered by the package price—one item per row (e.g. “Kathmandu–Lukla flights”).
   */
  included: {
    /**
     * Inclusion detail.
     */
    item: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'treks';
        value: string | Trek;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treks_select".
 */
export interface TreksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  gallery?: T;
  price?:
    | T
    | {
        amount?: T;
        currency?: T;
      };
  durationDays?: T;
  summary?: T;
  highlights?:
    | T
    | {
        value?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the header settings for your site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Upload your logo here. It will be displayed in the header.
   */
  logo: string | Media;
  /**
   * Text for the "Book Now" button in the header.
   */
  Book_now_button_text: string;
  /**
   * Color for the "Book Now" button in the header.Hex code/rgb value/color name
   */
  Book_now_button_color: string;
  /**
   * Add navigation links for the header. Each link should have a label and a URL.
   */
  navigation_links?:
    | {
        /**
         * Text for the navigation link.
         */
        label: string;
        /**
         * URL for the navigation link. Use absolute URLs or relative paths.
         */
        section_id: 'home' | 'about' | 'contact' | 'treks';
        id?: string | null;
      }[]
    | null;
  /**
   * Color for the navigation links when hovered over. Use hex code/rgb value/color name.
   */
  Navigation_links_hover_color?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the Landing page settings for your site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_page".
 */
export interface LandingPage {
  id: string;
  /**
   * Upload the background image for the landing page.
   */
  landing_page_background_image: string | Media;
  /**
   * Heading for the search bar in the header.
   */
  Search_bar_heading?: string | null;
  /**
   * Searchbar placeholder.
   */
  Search_bar_placeholder?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the Treks page settings for your site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treks_page".
 */
export interface TreksPage {
  id: string;
  /**
   * Heading for the Treks page.
   */
  treks_page_heading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  Book_now_button_text?: T;
  Book_now_button_color?: T;
  navigation_links?:
    | T
    | {
        label?: T;
        section_id?: T;
        id?: T;
      };
  Navigation_links_hover_color?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  landing_page_background_image?: T;
  Search_bar_heading?: T;
  Search_bar_placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treks_page_select".
 */
export interface TreksPageSelect<T extends boolean = true> {
  treks_page_heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}